module RecategorizeFoods
  def self.run
    # Mapping of keywords to categories
    category_mapping = {
      "farinha" => "Cereais e derivados",
      "cereal" => "Cereais e derivados",
      "pão" => "Cereais e derivados",
      "arroz" => "Cereais e derivados",
      "trigo" => "Cereais e derivados",
      "milho" => "Cereais e derivados",
      "aveia" => "Cereais e derivados",
      "centeio" => "Cereais e derivados",
      "cevada" => "Cereais e derivados",
      "macarrão" => "Cereais e derivados",
      "massa" => "Cereais e derivados",
      "biscoito" => "Cereais e derivados",
      "bolo" => "Cereais e derivados",
      "mingau" => "Cereais e derivados",
      "pamonha" => "Cereais e derivados",
      "polenta" => "Cereais e derivados",
      "carne" => "Carnes e derivados",
      "frango" => "Carnes e derivados",
      "fígado" => "Carnes e derivados",
      "peixe" => "Pescados e frutos do mar",
      "corimba" => "Pescados e frutos do mar",
      "tucunaré" => "Pescados e frutos do mar",
      "bacalhau" => "Pescados e frutos do mar",
      "cação" => "Pescados e frutos do mar",
      "camarão" => "Pescados e frutos do mar",
      "caranguejo" => "Pescados e frutos do mar",
      "gambá" => "Pescados e frutos do mar",
      "lula" => "Pescados e frutos do mar",
      "polvo" => "Pescados e frutos do mar",
      "salmão" => "Pescados e frutos do mar",
      "sardinha" => "Pescados e frutos do mar",
      "atum" => "Pescados e frutos do mar",
      "tilápia" => "Pescados e frutos do mar",
      "truta" => "Pescados e frutos do mar",
      "ostra" => "Pescados e frutos do mar",
      "mexilhão" => "Pescados e frutos do mar",
      "fruto do mar" => "Pescados e frutos do mar",
      "leite" => "Leite e derivados",
      "queijo" => "Leite e derivados",
      "ovo" => "Ovos e derivados",
      "uva" => "Frutas e derivados",
      "maçã" => "Frutas e derivados",
      "banana" => "Frutas e derivados",
      "laranja" => "Frutas e derivados",
      "morango" => "Frutas e derivados",
      "melancia" => "Frutas e derivados",
      "melão" => "Frutas e derivados",
      "pêssego" => "Frutas e derivados",
      "manga" => "Frutas e derivados",
      "abacaxi" => "Frutas e derivados",
      "cereja" => "Frutas e derivados",
      "ameixa" => "Frutas e derivados",
      "framboesa" => "Frutas e derivados",
      "carambola" => "Frutas e derivados",
      "ciriguela" => "Frutas e derivados",
      "cupuaçu" => "Frutas e derivados",
      "figo" => "Frutas e derivados",
      "goiaba" => "Frutas e derivados",
      "jabuticaba" => "Frutas e derivados",
      "jaca" => "Frutas e derivados",
      "kiwi" => "Frutas e derivados",
      "lichia" => "Frutas e derivados",
      "lima" => "Frutas e derivados",
      "limão" => "Frutas e derivados",
      "mirtilo" => "Frutas e derivados",
      "mirtilo" => "Frutas e derivados",
      "nespera" => "Frutas e derivados",
      "pera" => "Frutas e derivados",
      "pitanga" => "Frutas e derivados",
      "romã" => "Frutas e derivados",
      "tangerina" => "Frutas e derivados",
      "graviola" => "Frutas e derivados",
      "jambo" => "Frutas e derivados",
      "macaúba" => "Frutas e derivados",
      "mamão" => "Frutas e derivados",
      "maracujá" => "Frutas e derivados",
      "mexerica" => "Frutas e derivados",
      "mirtilo" => "Frutas e derivados",
      "pitaia" => "Frutas e derivados",
      "seriguela" => "Frutas e derivados",
      "tamarindo" => "Frutas e derivados",
      "tâmara" => "Frutas e derivados",
      "toranja" => "Frutas e derivados",
      "umbu" => "Frutas e derivados",
      "urucum" => "Frutas e derivados",
      "uva espinha" => "Frutas e derivados",
      "fruta" => "Frutas e derivados",
      "batata" => "Verduras, hortaliças e derivados",
      "abóbora" => "Verduras, hortaliças e derivados",
      "cenoura" => "Verduras, hortaliças e derivados",
      "repolho" => "Verduras, hortaliças e derivados",
      "alface" => "Verduras, hortaliças e derivados",
      "tomate" => "Verduras, hortaliças e derivados",
      "cebola" => "Verduras, hortaliças e derivados",
      "alho" => "Verduras, hortaliças e derivados",
      "pimentão" => "Verduras, hortaliças e derivados",
      "brócolis" => "Verduras, hortaliças e derivados",
      "couve" => "Verduras, hortaliças e derivados",
      "beterraba" => "Verduras, hortaliças e derivados",
      "berinjela" => "Verduras, hortaliças e derivados",
      "rabanete" => "Verduras, hortaliças e derivados",
      "espinafre" => "Verduras, hortaliças e derivados",
      "cará" => "Verduras, hortaliças e derivados",
      "caruru" => "Verduras, hortaliças e derivados",
      "catalonha" => "Verduras, hortaliças e derivados",
      "cebolinha" => "Verduras, hortaliças e derivados",
      "chicória" => "Verduras, hortaliças e derivados",
      "chuchu" => "Verduras, hortaliças e derivados",
      "coentro" => "Verduras, hortaliças e derivados",
      "endívia" => "Verduras, hortaliças e derivados",
      "acelga" => "Verduras, hortaliças e derivados",
      "mostarda" => "Verduras, hortaliças e derivados",
      "rúcula" => "Verduras, hortaliças e derivados",
      "hortelã" => "Verduras, hortaliças e derivados",
      "manjericão" => "Verduras, hortaliças e derivados",
      "salsinha" => "Verduras, hortaliças e derivados",
      "salsa" => "Verduras, hortaliças e derivados",
      "nabo" => "Verduras, hortaliças e derivados",
      "menta" => "Verduras, hortaliças e derivados",
      "inhame" => "Verduras, hortaliças e derivados",
      "jiló" => "Verduras, hortaliças e derivados",
      "jurubeba" => "Verduras, hortaliças e derivados",
      "mandioca" => "Verduras, hortaliças e derivados",
      "maxixe" => "Verduras, hortaliças e derivados",
      "palmito" => "Verduras, hortaliças e derivados",
      "taioba" => "Verduras, hortaliças e derivados",
      "taro" => "Verduras, hortaliças e derivados",
      "batata doce" => "Verduras, hortaliças e derivados",
      "pepino" => "Verduras, hortaliças e derivados",
      "quiabo" => "Verduras, hortaliças e derivados",
      "serralha" => "Verduras, hortaliças e derivados",
      "vagem" => "Verduras, hortaliças e derivados",
      "raiz" => "Verduras, hortaliças e derivados",
      "tubérculo" => "Verduras, hortaliças e derivados",
      "verdura" => "Verduras, hortaliças e derivados",
      "hortaliça" => "Verduras, hortaliças e derivados",
      "legume" => "Verduras, hortaliças e derivados",
      "feijão" => "Leguminosas e derivados",
      "grão" => "Leguminosas e derivados",
      "lentilha" => "Leguminosas e derivados",
      "ervilha" => "Leguminosas e derivados",
      "grão de bico" => "Leguminosas e derivados",
      "bebida" => "Bebidas (alcoólicas e não alcoólicas)",
      "vinho" => "Bebidas (alcoólicas e não alcoólicas)",
      "cerveja" => "Bebidas (alcoólicas e não alcoólicas)",
      "suco" => "Bebidas (alcoólicas e não alcoólicas)",
      "água" => "Bebidas (alcoólicas e não alcoólicas)",
      "chá" => "Bebidas (alcoólicas e não alcoólicas)",
      "café" => "Bebidas (alcoólicas e não alcoólicas)",
      "óleo" => "Gorduras e óleos",
      "manteiga" => "Gorduras e óleos",
      "gordura" => "Gorduras e óleos",
      "azeite" => "Gorduras e óleos",
      "banha" => "Gorduras e óleos",
      "castanha" => "Nozes e sementes",
      "amêndoa" => "Nozes e sementes",
      "noz" => "Nozes e sementes",
      "semente" => "Nozes e sementes",
      "amendoim" => "Nozes e sementes",
      "pistache" => "Nozes e sementes",
      "açúcar" => "Produtos açucarados",
      "doce" => "Produtos açucarados",
      "chocolate" => "Produtos açucarados",
      "mel" => "Produtos açucarados"
    }

    foods = Food.where(category: "Número do")
    updated_count = 0
    uncategorized = []

    foods.each do |food|
      name_lower = food.name.downcase

      # Find matching category
      matched_category = category_mapping.find { |keyword, _| name_lower.include?(keyword) }

      if matched_category
        new_category = matched_category[1]
        food.update(category: new_category)
        updated_count += 1
      else
        # Fallback: assign to Miscelâneas if no match found
        food.update(category: "Miscelâneas")
        uncategorized << food.name
      end
    end

    puts "Updated #{updated_count} foods with keyword matching"
    puts "Assigned #{uncategorized.length} foods to 'Miscelâneas' (fallback)"
    puts "\nFallback foods assigned to 'Miscelâneas':"
    uncategorized.first(15).each { |name| puts "  - #{name}" }
    puts "  ... and #{uncategorized.length - 15} more" if uncategorized.length > 15
  end
end
